defaults:
  contract:
    min_order_size: 0.001
    price_precision: 2
  max_leverage: 50
  min_leverage: 3
  timeframes:
  - 1m
  - 5m
  - 15m
  - 1h
  - 4h
  - 1d
symbols:
  ADAUSDT:
    contract:
      min_order_size: 1.0
      price_precision: 4
    max_leverage: 5
    min_leverage: 1
    timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 4h
    - 1d
  BTCUSDT:
    contract:
      min_order_size: 0.0001
      price_precision: 2
    enabled: false
    max_leverage: 5
    min_leverage: 1
    timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 4h
    - 1d
  DOGEUSDT:
    contract:
      min_order_size: 10.0
      price_precision: 5
    max_leverage: 5
    min_leverage: 1
    timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 4h
    - 1d
  ETHUSDT:
    contract:
      min_order_size: 0.01
      price_precision: 2
    enabled: false
    max_leverage: 5
    min_leverage: 1
    timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 4h
    - 1d
  SOLUSDT:
    contract:
      min_order_size: 0.1
      price_precision: 3
    max_leverage: 5
    min_leverage: 1
    timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 4h
    - 1d
  XRPUSDT:
    contract:
      min_order_size: 1.0
      price_precision: 4
    max_leverage: 5
    min_leverage: 1
    timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 4h
    - 1d
version: 1.0.0
