# config/trading/risk.yaml
limits:
  max_leverage: 3.0
  max_open_positions: 6
  max_exposure_per_symbol_usdt: 50000
  min_qty: 0.0001
  max_qty: 1000000
  cooldown_minutes: 0
  dd_day_pct: 5.0

# Configuración del planner
planner:
  thresholds:
    direction_confidence_min: 0.25  # Umbral mínimo de confianza para direction (reducido)
    regime_required: "range"         # Regime requerido para generar planes (cambiado a range)
    smc_alignment: false             # Requiere alineación SMC con direction (desactivado)
  gating:
    # Reglas de gating jerárquico
    require_all_heads: true          # Requiere predicciones de todos los heads
    direction_long_smc: "bull"       # SMC requerido para direction=long
    direction_short_smc: "bear"      # SMC requerido para direction=short
