# Configuración del procesamiento de señales
# Convierte predicciones de agentpreds a señales de trading en agentsignals

signal_processing:
  # Configuración general
  batch_size: 1000
  lookback_minutes: 5
  min_confidence: 0.6
  min_strength: 0.1
  side_threshold: 0.5
  
  # Filtros aplicados a las señales
  filters:
    - duplicate_filter      # Evitar señales duplicadas
    - time_filter          # Filtro por tiempo mínimo entre señales
    - confidence_filter    # Filtro por confianza mínima
    - strength_filter      # Filtro por fuerza mínima
  
  # Cálculo de fuerza de la señal
  strength_calculation: "abs(prob - 0.5)"
  
  # Configuración para tiempo real
  realtime:
    enabled: true
    interval_seconds: 30
    max_signals_per_batch: 100
    
  # Configuración para procesamiento en lote
  batch:
    enabled: true
    schedule: "0 */5 * * *"  # Cada 5 minutos
    max_lookback_hours: 24
    
  # Reglas de conversión de predicciones a señales
  conversion_rules:
    # Umbrales para generar señales
    min_prob_up: 0.6        # Probabilidad mínima para señal alcista
    max_prob_down: 0.4      # Probabilidad máxima para señal bajista
    
    # Cálculo de fuerza
    strength_multiplier: 2.0  # Multiplicador para la fuerza (0-1)
    
    # Metadatos adicionales
    include_confidence: true
    include_latency: true
    include_features_count: true
    
  # Configuración de base de datos
  database:
    connection_pool_size: 10
    batch_insert_size: 500
    retry_attempts: 3
    retry_delay_seconds: 1
    
  # Logging y monitoreo
  logging:
    level: "INFO"
    log_predictions: false
    log_signals: true
    log_performance: true
    
  # Métricas y alertas
  metrics:
    track_latency: true
    track_throughput: true
    alert_on_errors: true
    max_error_rate: 0.05  # 5% máximo de errores
