# paths.yaml - Rutas para datos, modelos, backups y logs
# Define ubicaciones para archivos y conexiones
# Usado por core/data/, core/ml/, scripts/
# Versión: 1.0.0

version: "1.0.0"

defaults:
  data: "data/"              # Directorio raíz para datos
  agents: "agents/"          # Directorio para modelos PPO
  logs: "logs/"              # Directorio para logs
  backups:                   # Directorio para backups
    models: "backups/models/"  # Modelos PPO
    logs: "backups/logs/"      # Logs históricos
  database:
    url: "postgresql://your_username:your_password@localhost:5432/trading_db"
    migrations: "db/migrations/"

paths:
  data:
    root: "data/"
    symbols:
      BTCUSDT: "data/BTCUSDT/"
      ETHUSDT: "data/ETHUSDT/"
      ADAUSDT: "data/ADAUSDT/"
      SOLUSDT: "data/SOLUSDT/"
      DOGEUSDT: "data/DOGEUSDT/"
      XRPUSDT: "data/XRPUSDT/"
  agents: "agents/"
  logs: "logs/"
  backups:
    models: "backups/models/"
    logs: "backups/logs/"
  database:
    url: "postgresql://postgres:160501@localhost:5432/trading_db"
    migrations: "db/migrations/"
