# Parámetros de backtest por motor
vectorized:
  fees_bps: 1.0
  slippage_bps: 0.5
  funding_apr: 0.05
  warmup_bars: 200
  random_windows:
    enabled: true
    n: 5
    min_days: 5
    max_days: 10

event_driven:
  fees_bps: 1.5
  slippage_bps: 1.0
  latency_ms: 80
  allow_partial_fills: true
  warmup_bars: 200

walk_forward:
  windows:
    - { train_days: 60, test_days: 15 }
    - { train_days: 90, test_days: 30 }

risk_overlay:
  max_exposure_usdt: 50000
  max_symbols: 6
  netting: true
