
# telegram.yaml - Configuración del bot Telegram
# Define comandos soportados y parámetros de comunicación
# Usado por core/control/telegram_interface.py
# Versión: 1.0.0

version: "1.0.0"

telegram:
  commands:                    # Comandos soportados
    start: "/start"           # Bienvenida
    status: "/status"         # Balance, PnL, drawdown, posiciones
    start_trading: "/start_trading"  # Inicia trading
    stop: "/stop"             # Detiene trading
    retrain: "/retrain"       # Reentrena agentes
    logs: "/logs"             # Trades, estrategias, logs
    init_db: "/init_db"       # Inicializa DB
    download_historical: "/download_historical"  # Descarga datos históricos
  response_time:              # Tiempos de respuesta (segundos)
    max_delay: 5.0           # Máximo retraso para responder (rango: 1.0-10.0)
    polling_interval: 1.0    # Intervalo de polling (rango: 0.5-5.0)
  notifications:               # Configuración de alertas
    enabled: true             # Enviar alertas
    types:                   # Tipos de alertas
      trades: true           # Notificar cada trade
      errors: true           # Notificar errores
      drawdowns: true        # Notificar drawdowns >5%
      status_updates: true   # Actualizaciones periódicas
    frequency:               # Frecuencia de alertas
      status_updates: 3600   # Cada hora (segundos, rango: 1800-86400)
