# Reglas de promoción y endurecimiento progresivo
thresholds:
  global:
    min_trades: 50
    sharpe_min: 0.3
    pf_min: 1.05
    max_dd_max: 0.50
    stability_min: 0.30
  ramp_up:
    cadence_days: 30
    step:
      sharpe_min: 0.05
      pf_min: 0.05
      max_dd_max: -0.02
      stability_min: 0.02

tie_breaker:
  - stability
  - sharpe
  - max_dd
# política de desempate (champion–challenger)
tie_breaker:
  - stability
  - max_dd
  - sharpe
