# rewards.yaml - Configuración avanzada de recompensas y penalizaciones para aprendizaje por refuerzo
# Define reglas para optimizar agentes PPO por categorías: performance, risk, activity, diversification
# Usado por core/ml/reinforcement_agent.py y core/ml/autolearn.py
# Versión: 1.0.0

version: "1.0.0"

defaults:
  weights:                    # Peso relativo de categorías (suma = 1.0)
    performance: 0.45        # Rentabilidad y métricas
    risk: 0.30               # Gestión de riesgos
    activity: 0.15           # Consistencia y actividad
    diversification: 0.10    # Diversificación entre símbolos
  performance:               # Recompensas por desempeño
    positive_pnl: 10.0       # Trade con PnL positivo (rango: 5.0-20.0)
    milestone_10pct: 50.0    # +10% balance (rango: 20.0-100.0)
    milestone_20pct: 100.0   # +20% balance (rango: 50.0-200.0)
    sharpe_above_2: 30.0     # Sharpe >2.0 (rango: 10.0-50.0)
    win_rate_above_60: 20.0  # Win rate >60% (rango: 10.0-40.0)
    negative_pnl: -5.0       # Trade con PnL negativo (rango: -10.0 a -2.0)
  risk:                      # Penalizaciones por riesgos
    drawdown_moderate:       # Drawdown 2-5% (rango: -10.0 a -5.0)
      threshold: 0.02
      penalty: -10.0
    drawdown_severe:         # Drawdown >5% (rango: -50.0 a -20.0)
      threshold: 0.05
      penalty: -50.0
    high_leverage_risk: -5.0 # >80% max_leverage (rango: -10.0 a -2.0)
  activity:                   # Recompensas/penalizaciones por actividad
    min_trades_per_day:      # Mínimo trades diarios (rango: 3-10)
      threshold: 5
      reward: 5.0            # Por alcanzar mínimo (rango: 2.0-10.0)
    inactivity: -2.0         # No operar en 1h (rango: -5.0 a -1.0)
    high_volatility: 5.0     # Operar en alta volatilidad (rango: 2.0-10.0)
  diversification:            # Recompensas por diversificación
    multi_symbol_trades: 10.0 # Operar 3+ símbolos en 24h (rango: 5.0-20.0)
    high_correlation: -5.0   # Trades correlacionados >0.8 (rango: -10.0 a -2.0)
  timeframe_weights:          # Ponderación de señales por timeframe (suma = 1.0)
    1m: 0.20
    5m: 0.30
    15m: 0.20
    1h: 0.15
    4h: 0.10
    1d: 0.05

symbols:
  BTCUSDT:
    performance:
      positive_pnl: 12.0
      milestone_10pct: 60.0
      milestone_20pct: 120.0
      sharpe_above_2: 35.0
      win_rate_above_60: 25.0
      negative_pnl: -6.0
    risk:
      drawdown_moderate:
        threshold: 0.02
        penalty: -12.0
      drawdown_severe:
        threshold: 0.05
        penalty: -60.0
      high_leverage_risk: -6.0
    activity:
      min_trades_per_day:
        threshold: 5
        reward: 6.0
      inactivity: -2.5
      high_volatility: 6.0
    diversification:
      multi_symbol_trades: 12.0
      high_correlation: -6.0
  ETHUSDT:
    performance:
      positive_pnl: 10.0
      milestone_10pct: 50.0
      milestone_20pct: 100.0
      sharpe_above_2: 30.0
      win_rate_above_60: 20.0
      negative_pnl: -5.0
    risk:
      drawdown_moderate:
        threshold: 0.02
        penalty: -10.0
      drawdown_severe:
        threshold: 0.05
        penalty: -50.0
      high_leverage_risk: -5.0
    activity:
      min_trades_per_day:
        threshold: 5
        reward: 5.0
      inactivity: -2.0
      high_volatility: 5.0
    diversification:
      multi_symbol_trades: 10.0
      high_correlation: -5.0
  ADAUSDT:
    performance:
      positive_pnl: 8.0
      milestone_10pct: 40.0
      milestone_20pct: 80.0
      sharpe_above_2: 25.0
      win_rate_above_60: 15.0
      negative_pnl: -4.0
    risk:
      drawdown_moderate:
        threshold: 0.02
        penalty: -8.0
      drawdown_severe:
        threshold: 0.05
        penalty: -40.0
      high_leverage_risk: -4.0
    activity:
      min_trades_per_day:
        threshold: 5
        reward: 4.0
      inactivity: -1.5
      high_volatility: 4.0
    diversification:
      multi_symbol_trades: 8.0
      high_correlation: -4.0
  SOLUSDT:
    performance:
      positive_pnl: 10.0
      milestone_10pct: 50.0
      milestone_20pct: 100.0
      sharpe_above_2: 30.0
      win_rate_above_60: 20.0
      negative_pnl: -5.0
    risk:
      drawdown_moderate:
        threshold: 0.02
        penalty: -10.0
      drawdown_severe:
        threshold: 0.05
        penalty: -50.0
      high_leverage_risk: -5.0
    activity:
      min_trades_per_day:
        threshold: 5
        reward: 5.0
      inactivity: -2.0
      high_volatility: 5.0
    diversification:
      multi_symbol_trades: 10.0
      high_correlation: -5.0
  DOGEUSDT:
    performance:
      positive_pnl: 8.0
      milestone_10pct: 40.0
      milestone_20pct: 80.0
      sharpe_above_2: 25.0
      win_rate_above_60: 15.0
      negative_pnl: -4.0
    risk:
      drawdown_moderate:
        threshold: 0.02
        penalty: -8.0
      drawdown_severe:
        threshold: 0.05
        penalty: -40.0
      high_leverage_risk: -4.0
    activity:
      min_trades_per_day:
        threshold: 5
        reward: 4.0
      inactivity: -1.5
      high_volatility: 4.0
    diversification:
      multi_symbol_trades: 8.0
      high_correlation: -4.0
  XRPUSDT:
    performance:
      positive_pnl: 8.0
      milestone_10pct: 40.0
      milestone_20pct: 80.0
      sharpe_above_2: 25.0
      win_rate_above_60: 15.0
      negative_pnl: -4.0
    risk:
      drawdown_moderate:
        threshold: 0.02
        penalty: -8.0
      drawdown_severe:
        threshold: 0.05
        penalty: -40.0
      high_leverage_risk: -4.0
    activity:
      min_trades_per_day:
        threshold: 5
        reward: 4.0
      inactivity: -1.5
      high_volatility: 4.0
    diversification:
      multi_symbol_trades: 8.0
      high_correlation: -4.0
