training:
  balance:
    initial: 1000.0
    target: 10000.0
    symbols:
      ADAUSDT:
        initial: 5000.0
        risk_per_trade: 0.005
        target: 5500.0
      BTCUSDT:
        initial: 1000.0
        risk_per_trade: 0.01
        target: 2000.0
      DOGEUSDT:
        initial: 3000.0
        risk_per_trade: 0.005
        target: 3300.0
      ETHUSDT:
        initial: 1000.0
        risk_per_trade: 0.01
        target: 2000.0
      SOLUSDT:
        initial: 6000.0
        risk_per_trade: 0.01
        target: 6600.0
      XRPUSDT:
        initial: 5000.0
        risk_per_trade: 0.005
        target: 5500.0
  hyperparameters:
    batch_size: 64
    ent_coef: 0.01
    gamma: 0.99
    learning_rate: 0.0003
    n_steps: 2048
  milestones:
    balance_10pct: 50.0
    balance_20pct: 100.0
    consecutive_wins:
      reward: 25.0
      threshold: 5
    sharpe_above_2: 30.0
    win_rate_above_60: 20.0
  modes:
    historical:
      enabled: true
      lookback_days: 365
      timesteps: 100000
    realtime:
      enabled: true
      lookback_days: 30
      timesteps: 50000
  objectives:
    max_drawdown: 0.05
    min_sharpe: 1.5
    min_trades_per_day: 5
    min_win_rate: 0.6
  overfitting_control:
    early_stopping:
      min_improvement: 0.01
      patience: 10000
    max_policy_entropy: 0.5
  simulation:
    fees: 0.0006
    slippage: 0.001
version: 1.0.0
